CREATE TABLE IF NOT EXISTS users (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(100) NOT NULL, email VARCHAR(190) NOT NULL UNIQUE,
 password_hash VARCHAR(255) NOT NULL, city VARCHAR(100) NOT NULL,
 phone VARCHAR(30) NOT NULL DEFAULT '', role ENUM('member','admin') NOT NULL DEFAULT 'member',
 active TINYINT(1) NOT NULL DEFAULT 1, session_version INT NOT NULL DEFAULT 1,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS categories (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(80) NOT NULL UNIQUE,
 icon VARCHAR(30) NOT NULL DEFAULT 'box', active TINYINT(1) NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS items (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, owner_id BIGINT UNSIGNED NOT NULL,
 category_id INT UNSIGNED NOT NULL, title VARCHAR(120) NOT NULL, description TEXT NOT NULL,
 daily_rate DECIMAL(10,2) NOT NULL, deposit DECIMAL(10,2) NOT NULL DEFAULT 0,
 city VARCHAR(100) NOT NULL, item_condition ENUM('Like new','Good','Fair') NOT NULL DEFAULT 'Good',
 image VARCHAR(150) DEFAULT NULL, available TINYINT(1) NOT NULL DEFAULT 1,
 hidden TINYINT(1) NOT NULL DEFAULT 0, deleted_at DATETIME DEFAULT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (owner_id) REFERENCES users(id), FOREIGN KEY (category_id) REFERENCES categories(id),
 INDEX browse (hidden,available,category_id), INDEX owner (owner_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS rentals (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, item_id BIGINT UNSIGNED NOT NULL,
 renter_id BIGINT UNSIGNED NOT NULL, start_date DATE NOT NULL, end_date DATE NOT NULL,
 days INT UNSIGNED NOT NULL, daily_rate DECIMAL(10,2) NOT NULL, total DECIMAL(12,2) NOT NULL,
 deposit DECIMAL(10,2) NOT NULL DEFAULT 0,
 status ENUM('pending','accepted','active','return_requested','completed','rejected','cancelled') NOT NULL DEFAULT 'pending',
 note VARCHAR(1000) NOT NULL DEFAULT '', created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY (item_id) REFERENCES items(id), FOREIGN KEY (renter_id) REFERENCES users(id),
 INDEX availability (item_id,status,start_date,end_date), INDEX renter (renter_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS reviews (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, rental_id BIGINT UNSIGNED NOT NULL UNIQUE,
 rating TINYINT UNSIGNED NOT NULL, comment VARCHAR(1000) NOT NULL DEFAULT '',
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (rental_id) REFERENCES rentals(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS messages (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, rental_id BIGINT UNSIGNED NOT NULL,
 sender_id BIGINT UNSIGNED NOT NULL, body VARCHAR(2000) NOT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (rental_id) REFERENCES rentals(id), FOREIGN KEY (sender_id) REFERENCES users(id),
 INDEX thread (rental_id,id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS contacts (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) NOT NULL,
 email VARCHAR(190) NOT NULL, subject VARCHAR(150) NOT NULL, body TEXT NOT NULL,
 resolved TINYINT(1) NOT NULL DEFAULT 0, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS password_resets (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL,
 token_hash CHAR(64) NOT NULL UNIQUE, expires_at DATETIME NOT NULL, used_at DATETIME DEFAULT NULL,
 FOREIGN KEY (user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
